export const API_ROUTES = {
  AVAILABILITY: {
    MATCH: '/availability/match/find',
    PROFILE: '/availability/profile/:mentorId',
  },
  AUTH: {
    SIGNUP: "/auth/signup",
    VERIFY_OTP: "/auth/signup/verify-otp",
    RESEND_OTP: "/auth/signup/resend-otp",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
  },
  ADMIN: {
    LOGIN: "/admin/login",
    LOGOUT: "/admin/logout",
    REFRESH: "/admin/refresh",
    MENTORS: "/admin/mentors",
    MENTOR_DETAILS: "/admin/mentors/:mentorId",
    MENTOR_APPROVE: "/admin/mentors/:mentorId/approve",
    MENTOR_REJECT: "/admin/mentors/:mentorId/reject",
    MENTOR_BLOCK: "/admin/mentors/:mentorId/block",
    MENTOR_UNBLOCK: "/admin/mentors/:mentorId/unblock",
    MENTOR_UPDATE: "/admin/mentors/:mentorId",
    STUDENTS: "/admin/students",
    STUDENTS_WITH_STATS: "/admin/students-with-stats",
    STUDENT_DETAILS: "/admin/students/:studentId",
    STUDENT_UPDATE: "/admin/students/:studentId",
    STUDENT_BLOCK: "/admin/students/:studentId/block",
    STUDENT_UNBLOCK: "/admin/students/:studentId/unblock",
    STUDENT_TRIAL_CLASSES: "/admin/students/:studentId/trial-classes",
    STUDENT_PROFILE: "/admin/students/:studentId/profile",
    TRIAL_CLASSES: "/admin/trial-classes",
    TRIAL_CLASS_DETAILS: "/admin/trial-classes/:trialClassId",
    TRIAL_CLASS_ASSIGN_MENTOR: "/admin/trial-classes/:trialClassId/assign-mentor",
    TRIAL_CLASS_STATUS: "/admin/trial-classes/:trialClassId/status",
    AVAILABLE_MENTORS: "/admin/available-mentors",
    MENTORS_AVAILABLE_FOR_COURSE: "/admin/mentors/available-for-course",
    ONE_TO_ONE_COURSES: "/admin/courses/one-to-one",
    ALL_COURSES: "/admin/courses/getAllCourses",
    GRADES: "/admin/grades",
    SUBJECTS: "/admin/subjects",
    TRANSACTIONS: "/admin/finance/transactions",
    ALL_ENROLLMENTS: "/admin/enrollments",
    STUDENT_ASSIGN_MENTOR: "/admin/student/assign-mentor",
    STUDENT_REASSIGN_MENTOR: '/admin/students/reassign-mentor',
    MENTOR_REQUESTS: '/admin/mentor-requests',
    MENTOR_REQUEST_APPROVE: '/admin/mentor-requests/:requestId/approve',
    MENTOR_REQUEST_REJECT: '/admin/mentor-requests/:requestId/reject',
  },
  MENTOR: {
    PROFILE_UPDATE: "/mentor/me/profile-update",
    SUBMIT_APPROVAL: "/mentor/me/submit-approval",
    PROFILE: "/mentor/me/profile",
    TRIAL_CLASSES: "/mentor/me/trial-classes",
    TRIAL_CLASS_STATUS: "/mentor/me/trial-classes/:id/status",
    COURSES: "/mentor/me/courses",
    // Admin routes accessed by mentor? The api file had /mentor/admin/... 
    // Wait, let's double check those. "authApi.get("/mentor/admin/pending")"
    // Usually that implies a /mentor/admin route prefix in backend.
    ADMIN_PENDING: "/mentor/admin/pending",
    ADMIN_APPROVE: "/mentor/admin/:mentorId/approve",
    ADMIN_REJECT: "/mentor/admin/:mentorId/reject",
  },
  STUDENT: {
    PROFILE: "/student/profile",
    TRIAL_CLASSES_REQUEST: "/student/trial-classes/request",
    TRIAL_CLASSES: "/student/trial-classes",
    TRIAL_CLASS_DETAILS: "/student/trial-classes/:id",
    TRIAL_CLASS_FEEDBACK: "/student/trial-classes/:trialClassId/feedback",
    TRIAL_CLASS_CANCEL: "/student/trial-classes/:trialClassId/cancel",
    MY_COURSES: "/student/courses",
    PAYMENT_HISTORY: "/student/payments",

    GRADES: "student/grades", 
    GRADES_SYLLABUS: "/student/grades/syllabus", 
    SUBJECTS: "student/subjects", 
    GET_BY_GRADE: "/student/subjects/grade", // Added this
    SUBJECTS_FILTER: "/student/subjects/filter",
  },
  COURSES: {
    AVAILABLE: "/courses/available", 
  },
  COURSE_REQUESTS: {
    BASE: "/course-requests",
    ALL: "/admin/course-requests",
    STATUS: "/admin/course-requests/:requestId/status",
  },
  ENROLLMENTS: {
    BASE: "/enrollments",
    ENROLL: "/enrollments/enroll/:courseId",
    MY_ENROLLMENTS: "/enrollments/my-enrollments",
  },
  ROLE: {
    VERIFY: "/role/verify",
    ROLE_ONLY: "/role-only",
    BY_ID: "/role/:userId",
  },
  VIDEO_CALL: {
    INITIALIZE: "/video-call/initialize",
    STATUS: "/video-call/status/:trialClassId",
    END: "/video-call/end",
  },
  TRIAL_CLASSES: {
    COMPLETE: "/trial-classes/:id/complete",
  },
};
