export enum AccessState {
  FORBIDDEN = 'FORBIDDEN',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PROFILE_COMPLETION = 'PROFILE_COMPLETION',
  TRIAL_BOOKING = 'TRIAL_BOOKING',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PREFERENCES_REQUIRED = 'PREFERENCES_REQUIRED',
  FULLY_QUALIFIED = 'FULLY_QUALIFIED',
}

export const ACCESS_STATE_HIERARCHY: Record<AccessState, number> = {
  [AccessState.FORBIDDEN]: 0,
  [AccessState.EMAIL_VERIFICATION]: 1,
  [AccessState.PROFILE_COMPLETION]: 2,
  [AccessState.TRIAL_BOOKING]: 3,
  [AccessState.PAYMENT_REQUIRED]: 4,
  [AccessState.PREFERENCES_REQUIRED]: 5,
  [AccessState.FULLY_QUALIFIED]: 6,
};
