export const AUTH_ROUTES = {
  GOOGLE: "/google",
  GOOGLE_CALLBACK: "/google/callback",
  SIGNUP: "/signup",
  SIGNUP_VERIFY_OTP: "/signup/verify-otp",
  SIGNUP_RESEND_OTP: "/signup/resend-otp",
  LOGIN: "/login",
  FORGOT_PASSWORD_SEND_OTP: "/forgot-password/send-otp",
  REFRESH: "/refresh",
  ME: "/me",
  LOGOUT: "/logout",
};

export const STUDENT_ROUTES = {
  TRIAL_CLASSES_REQUEST: "/trial-classes/request",
  TRIAL_CLASSES: "/trial-classes",
  TRIAL_CLASS_BY_ID: "/trial-classes/:id",
  TRIAL_CLASS_FEEDBACK: "/trial-classes/:id/feedback",
  AVAILABLE_SLOTS: "/trial-classes/available-slots", // Added this
  GRADES: "/grades",
  GRADES_SYLLABUS: "/grades/syllabus",
  SUBJECTS: "/subjects",
  SUBJECTS_GRADE: "/subjects/grade",
  SUBJECTS_FILTER: "/subjects/filter",
  COURSE_REQUEST: "/course-request",
  AVAILABLE_COURSES: "/available-courses",
  MY_COURSES: "/courses",
  PAYMENTS: "/payments",
  PROFILE: "/profile",
  PREFERENCES: "/preferences",
  STUDY_MATERIALS: "/study-materials",
};

export const ADMIN_ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  MENTORS: "/mentors",
  MENTORS_AVAILABLE_FOR_COURSE: "/mentors/available-for-course",
  MENTOR_PROFILE: "/mentors/:mentorId",
  MENTOR_APPROVE: "/mentors/:mentorId/approve",
  MENTOR_REJECT: "/mentors/:mentorId/reject",
  MENTOR_BLOCK: "/mentors/:mentorId/block",
  MENTOR_UNBLOCK: "/mentors/:mentorId/unBlock",
  MENTOR_UPDATE: "/mentors/:mentorId",
  STUDENTS: "/students",
  STUDENTS_WITH_STATS: "/students-with-stats",
  STUDENT_UPDATE: "/students/:studentId",
  STUDENT_TRIAL_CLASSES: "/students/:studentId/trial-classes",
  STUDENT_PROFILE: "/students/:studentId/profile",
  REFRESH: "/refresh",
  TRIAL_CLASSES: "/trial-classes",
  TRIAL_CLASS_DETAILS: "/trial-classes/:trialClassId",
  TRIAL_CLASS_ASSIGN_MENTOR: "/trial-classes/:trialClassId/assign-mentor",
  TRIAL_CLASS_STATUS: "/trial-classes/:trialClassId/status",
  AVAILABLE_MENTORS: "/available-mentors",
  COURSES_ONE_TO_ONE: "/courses/one-to-one",
  ALL_COURSES: "/courses/getAllCourses",
  GRADES: "/grades",
  SUBJECTS: "/subjects",
  COURSE_REQUESTS: "/course-requests",
  COURSE_REQUEST_STATUS: "/course-requests/:id/status",
  ENROLLMENTS: "/enrollments",
  MENTOR_REQUESTS: "/mentor-requests",
  MENTOR_LEAVE_APPROVE: "/mentors/:mentorId/leave/:leaveId/approve",
};

export const MENTOR_ROUTES = {
  PROFILE_UPDATE: "/me/profile-update",
  SUBMIT_APPROVAL: "/me/submit-approval",
  TRIAL_CLASSES: "/me/trial-classes",
  TRIAL_CLASS_STATUS: "/me/trial-classes/:id/status",
  PROFILE: "/me/profile",
  COURSES: "/me/courses",
  AVAILABLE_SLOTS: "/:mentorId/available-slots",
  STUDY_MATERIALS: "/sessions/:sessionId/study-materials",
  STUDY_MATERIAL_DELETE: "/study-materials/:materialId",
  LEAVE_REQUEST: "/me/leave",
  SESSIONS: "/sessions",
  UPCOMING_SESSIONS: "/me/sessions/upcoming",
  STUDENTS_ONE_TO_ONE: "/students/one-to-one",
  BATCHES: "/batches",
};
