export enum BookingEligibility {
  ELIGIBLE = 'ELIGIBLE',
  OVERLAP = 'OVERLAP',
  SLOT_FULL = 'SLOT_FULL',
  PLAN_MISMATCH = 'PLAN_MISMATCH',
  MENTOR_LIMIT_REACHED = 'MENTOR_LIMIT_REACHED',
  FORBIDDEN = 'FORBIDDEN', 
}

export const SCHEDULING_CONFIG = {
  MIN_CANCELLATION_HOURS: 12, 
  RESCHEDULE_WINDOW_HOURS: 24,
  DEFAULT_MAX_STUDENTS_PER_MENTOR: 1, 
};
